// <auto-generated />
using System;
using LabSchool.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabSchool.Migrations
{
    [DbContext(typeof(LabSchoolContext))]
    partial class LabSchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabSchool.Models.Aluno", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Codigo");

                    b.ToTable("Aluno", (string)null);

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            DataDeNascimento = new DateTime(1979, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manu@gmail.com",
                            Nome = "Bart Simpson"
                        },
                        new
                        {
                            Codigo = 2,
                            DataDeNascimento = new DateTime(1981, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "JonasManu@gmail.com",
                            Nome = "Lisa Simpson"
                        },
                        new
                        {
                            Codigo = 3,
                            DataDeNascimento = new DateTime(1965, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manuzinho@gmail.com",
                            Nome = "Marge Simpson"
                        },
                        new
                        {
                            Codigo = 4,
                            DataDeNascimento = new DateTime(1981, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "EuMesmo@gmail.com",
                            Nome = "Milhouse Van Houten"
                        },
                        new
                        {
                            Codigo = 5,
                            DataDeNascimento = new DateTime(1975, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manu@gmail.com",
                            Nome = "Nelson Muntz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
